### ISSUE TITLE
[help]: Unknown connection ID

### ISSUE THREAD

**Issue by qlanto224** [stuzero/pg-mcp-server#16]
![image](https://github.com/user-attachments/assets/a0337a63-971e-4fee-bbdd-b9f4088beab7)

**Comment by stuzero** [comment]
Apologies, I seem to have accidentally deleted you original message

**Comment by stuzero** [comment]
What agent are you using?

**Comment by qlanto224** [comment]
> What agent are you using?

dify.

**Comment by qlanto224** [comment]
Sorry, I don't know if it's a mistake in my understanding. I used the docker deployment method, but setting `DATABASE_URL` and `LOG_LEVEL` using environment variables didn't take effect.
This is my `docker-compose.yml`
```yaml
version: '3.8'

services:
  pg-mcp:
    image: mcp-mcp-pg:latest
    container_name: pg-mcp
    ports:
      - "7999:8000"
    environment:
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Shanghai
      - PG_MCP_URL=http://192.168.3.37:7999/sse
      - DATABASE_URL=postgresql://user:pwd@192.168.3.22:5432/mid_test
      # - ANTHROPIC_API_KEY=your-anthropic-api-key
      # - GEMINI_API_KEY=your-gemini-api-key
    volumes:
      # For development: mount app directory to enable hot-reloading
      - ./pg-mcp-server/server:/app/server
    restart: unless-stopped
    networks:
      - mcp_net


networks:
  mcp_net:
    driver: bridge
    ipam:
      config:
        - subnet: 112.30.0.0/16
```
